name: On pull request
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: read
jobs:
  test:
    strategy:
    runs-on: ubuntu-20.04
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: "client-sdk-go-test"
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Commitlint and Other Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - run: goimports -l -w $(ls -d */*/ | grep -v "internal/protos/") ./momento
      - run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          skip-pkg-cache: true

      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: official
          project_stability: experimental
          project_type: sdk
          sdk_language: Go
          usage_example_path: ./examples/main.go

      - name: Run test
        run: |
          go vet ./...
          go test -v ./momento


