name: Push to main

on:
  push:
    branches: [main]

jobs:
  build_go:
    runs-on: ubuntu-20.04
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: "client-sdk-go-test"
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - run: goimports -l -w $(ls -d */*/ | grep -v "internal/protos/") ./momento

      - run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true

      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi

      - name: Run test
        run: |
          go vet ./...
          go test -v ./momento ./incubating

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v1
        with:
          project_status: official
          project_stability: alpha
          project_type: sdk
          sdk_language: Go
          usage_example_path: ./examples/main.go
