name: Test

on:
  workflow_call:
    secrets:
      auth-token:
        description: "Auth token used for live testing"
        required: true
      github-token:
        description: "Token for running Github actions"
        required: true

jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      TEST_AUTH_TOKEN: ${{ secrets.auth-token }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install devtools
        run: make install-devtools

      - name: Lint
        run: make lint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          skip-pkg-cache: true

      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git diff
            exit 1
          fi

      - name: Build
        run: make build

      - name: Build examples
        run: make build-examples

      - name: Run test
        run: make test
